// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aura-premium/ChromaticEditorial.tsx": () => import("../components/mockups/aura-premium/ChromaticEditorial.tsx"),
  "./components/mockups/aura-premium/ClinicalBlanc.tsx": () => import("../components/mockups/aura-premium/ClinicalBlanc.tsx"),
  "./components/mockups/aura-premium/ObsidianMaison.tsx": () => import("../components/mockups/aura-premium/ObsidianMaison.tsx")
};
