/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as MarcasRouteImport } from './routes/marcas'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AudifonosRouteImport } from './routes/audifonos'
import { Route as AccesoriosRouteImport } from './routes/accesorios'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoSlugRouteImport } from './routes/catalogo.$slug'
import { Route as AuthenticatedAdminCatalogoRouteImport } from './routes/_authenticated/admin.catalogo'
import { Route as AuthenticatedAdminCatalogoIdRouteImport } from './routes/_authenticated/admin.catalogo.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRoute = MarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AudifonosRoute = AudifonosRouteImport.update({
  id: '/audifonos',
  path: '/audifonos',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoriosRoute = AccesoriosRouteImport.update({
  id: '/accesorios',
  path: '/accesorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoSlugRoute = CatalogoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CatalogoRoute,
} as any)
const AuthenticatedAdminCatalogoRoute =
  AuthenticatedAdminCatalogoRouteImport.update({
    id: '/admin/catalogo',
    path: '/admin/catalogo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCatalogoIdRoute =
  AuthenticatedAdminCatalogoIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCatalogoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRoute
  '/audifonos': typeof AudifonosRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/marcas': typeof MarcasRoute
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRouteWithChildren
  '/admin/catalogo/$id': typeof AuthenticatedAdminCatalogoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRoute
  '/audifonos': typeof AudifonosRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/marcas': typeof MarcasRoute
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRouteWithChildren
  '/admin/catalogo/$id': typeof AuthenticatedAdminCatalogoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accesorios': typeof AccesoriosRoute
  '/audifonos': typeof AudifonosRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/marcas': typeof MarcasRoute
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/_authenticated/admin/catalogo': typeof AuthenticatedAdminCatalogoRouteWithChildren
  '/_authenticated/admin/catalogo/$id': typeof AuthenticatedAdminCatalogoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accesorios'
    | '/audifonos'
    | '/auth'
    | '/blog'
    | '/catalogo'
    | '/contacto'
    | '/faq'
    | '/marcas'
    | '/nosotros'
    | '/servicios'
    | '/sitemap.xml'
    | '/catalogo/$slug'
    | '/admin/catalogo'
    | '/admin/catalogo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accesorios'
    | '/audifonos'
    | '/auth'
    | '/blog'
    | '/catalogo'
    | '/contacto'
    | '/faq'
    | '/marcas'
    | '/nosotros'
    | '/servicios'
    | '/sitemap.xml'
    | '/catalogo/$slug'
    | '/admin/catalogo'
    | '/admin/catalogo/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accesorios'
    | '/audifonos'
    | '/auth'
    | '/blog'
    | '/catalogo'
    | '/contacto'
    | '/faq'
    | '/marcas'
    | '/nosotros'
    | '/servicios'
    | '/sitemap.xml'
    | '/catalogo/$slug'
    | '/_authenticated/admin/catalogo'
    | '/_authenticated/admin/catalogo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccesoriosRoute: typeof AccesoriosRoute
  AudifonosRoute: typeof AudifonosRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  CatalogoRoute: typeof CatalogoRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  FaqRoute: typeof FaqRoute
  MarcasRoute: typeof MarcasRoute
  NosotrosRoute: typeof NosotrosRoute
  ServiciosRoute: typeof ServiciosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audifonos': {
      id: '/audifonos'
      path: '/audifonos'
      fullPath: '/audifonos'
      preLoaderRoute: typeof AudifonosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accesorios': {
      id: '/accesorios'
      path: '/accesorios'
      fullPath: '/accesorios'
      preLoaderRoute: typeof AccesoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$slug': {
      id: '/catalogo/$slug'
      path: '/$slug'
      fullPath: '/catalogo/$slug'
      preLoaderRoute: typeof CatalogoSlugRouteImport
      parentRoute: typeof CatalogoRoute
    }
    '/_authenticated/admin/catalogo': {
      id: '/_authenticated/admin/catalogo'
      path: '/admin/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AuthenticatedAdminCatalogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/catalogo/$id': {
      id: '/_authenticated/admin/catalogo/$id'
      path: '/$id'
      fullPath: '/admin/catalogo/$id'
      preLoaderRoute: typeof AuthenticatedAdminCatalogoIdRouteImport
      parentRoute: typeof AuthenticatedAdminCatalogoRoute
    }
  }
}

interface AuthenticatedAdminCatalogoRouteChildren {
  AuthenticatedAdminCatalogoIdRoute: typeof AuthenticatedAdminCatalogoIdRoute
}

const AuthenticatedAdminCatalogoRouteChildren: AuthenticatedAdminCatalogoRouteChildren =
  {
    AuthenticatedAdminCatalogoIdRoute: AuthenticatedAdminCatalogoIdRoute,
  }

const AuthenticatedAdminCatalogoRouteWithChildren =
  AuthenticatedAdminCatalogoRoute._addFileChildren(
    AuthenticatedAdminCatalogoRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCatalogoRoute: typeof AuthenticatedAdminCatalogoRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCatalogoRoute: AuthenticatedAdminCatalogoRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CatalogoRouteChildren {
  CatalogoSlugRoute: typeof CatalogoSlugRoute
}

const CatalogoRouteChildren: CatalogoRouteChildren = {
  CatalogoSlugRoute: CatalogoSlugRoute,
}

const CatalogoRouteWithChildren = CatalogoRoute._addFileChildren(
  CatalogoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccesoriosRoute: AccesoriosRoute,
  AudifonosRoute: AudifonosRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  CatalogoRoute: CatalogoRouteWithChildren,
  ContactoRoute: ContactoRoute,
  FaqRoute: FaqRoute,
  MarcasRoute: MarcasRoute,
  NosotrosRoute: NosotrosRoute,
  ServiciosRoute: ServiciosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
